In [4]:
!pip install featuretools

import pandas as pd
import numpy as np

# featuretools for automated feature engineering
import featuretools as ft

# matplotlit and seaborn for visualizations
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = 22
import seaborn as sns

Collecting featuretools
  Downloading https://files.pythonhosted.org/packages/a6/55/5e206fff0ecfec66e9d95248a9302b0d691f1312afa71e96323a83963e19/featuretools-0.20.0-py3-none-any.whl (287kB)
     |████████████████████████████████| 296kB 4.2MB/s
Requirement already satisfied: psutil>=5.4.8 in /usr/local/lib/python3.6/dist-packages (from featuretools) (5.4.8)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.6/dist-packages (from featuretools) (1.4.1)
Requirement already satisfied: cloudpickle>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from featuretools) (1.3.0)
Requirement already satisfied: dask[dataframe]>=2.12.0 in /usr/local/lib/python3.6/dist-packages (from featuretools) (2.12.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from featuretools) (1.18.5)
Requirement already satisfied: click>=7.0.0 in /usr/local/lib/python3.6/dist-packages (from featuretools) (7.1.2)
Collecting distributed>=2.12.0
  Downloading https://files.pythonhosted.org/packages/4e/39/665a3b952ac889839eead70813dbc638fe49be4c6217ed249fc06b6485fa/distributed-2.30.0-py3-none-any.whl (656kB)
     |████████████████████████████████| 665kB 13.7MB/s
Requirement already satisfied: pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1 in /usr/local/lib/python3.6/dist-packages (from featuretools) (1.1.3)
Requirement already satisfied: tqdm>=4.32.0 in /usr/local/lib/python3.6/dist-packages (from featuretools) (4.41.1)
Requirement already satisfied: pyyaml>=3.12 in /usr/local/lib/python3.6/dist-packages (from featuretools) (3.13)
Requirement already satisfied: toolz>=0.7.3; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]>=2.12.0->featuretools) (0.11.1)
Collecting fsspec>=0.6.0; extra == "dataframe"
  Downloading https://files.pythonhosted.org/packages/a5/8b/1df260f860f17cb08698170153ef7db672c497c1840dcc8613ce26a8a005/fsspec-0.8.4-py3-none-any.whl (91kB)
     |████████████████████████████████| 92kB 9.3MB/s
Collecting partd>=0.3.10; extra == "dataframe"
  Downloading https://files.pythonhosted.org/packages/44/e1/68dbe731c9c067655bff1eca5b7d40c20ca4b23fd5ec9f3d17e201a6f36b/partd-1.1.0-py3-none-any.whl
Requirement already satisfied: tornado>=5; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (5.1.1)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (1.7.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (2.0.0)
Collecting contextvars; python_version < "3.7"
  Downloading https://files.pythonhosted.org/packages/83/96/55b82d9f13763be9d672622e1b8106c85acb83edd7cc2fa5bc67cd9877e9/contextvars-2.4.tar.gz
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (2.2.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (50.3.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.12.0->featuretools) (1.0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (2.8.1)
Collecting locket
  Downloading https://files.pythonhosted.org/packages/d0/22/3c0f97614e0be8386542facb3a7dcfc2584f7b83608c02333bced641281c/locket-0.2.0.tar.gz
Requirement already satisfied: heapdict in /usr/local/lib/python3.6/dist-packages (from zict>=0.1.3->distributed>=2.12.0->featuretools) (1.0.1)
Collecting immutables>=0.9
  Downloading https://files.pythonhosted.org/packages/99/e0/ea6fd4697120327d26773b5a84853f897a68e33d3f9376b00a8ff96e4f63/immutables-0.14-cp36-cp36m-manylinux1_x86_64.whl (98kB)
     |████████████████████████████████| 102kB 8.3MB/s
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (1.15.0)
Building wheels for collected packages: contextvars, locket
  Building wheel for contextvars (setup.py) ... done
  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7666 sha256=e887b39b07227c345f8b61af4a425fdcb8963911d40173d66e563b2a52bf5337
  Stored in directory: /root/.cache/pip/wheels/a5/7d/68/1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de
  Building wheel for locket (setup.py) ... done
  Created wheel for locket: filename=locket-0.2.0-cp36-none-any.whl size=4040 sha256=aaaed44971217706682c9d95091e281371b8598949fb39d2112d922165cbf36c
  Stored in directory: /root/.cache/pip/wheels/26/1e/e8/4fa236ec931b1a0cdd61578e20d4934d7bf188858723b84698
Successfully built contextvars locket
ERROR: distributed 2.30.0 has requirement cloudpickle>=1.5.0, but you'll have cloudpickle 1.3.0 which is incompatible.
Installing collected packages: immutables, contextvars, distributed, featuretools, fsspec, locket, partd
  Found existing installation: distributed 1.25.3
    Uninstalling distributed-1.25.3:
      Successfully uninstalled distributed-1.25.3
Successfully installed contextvars-2.4 distributed-2.30.0 featuretools-0.20.0 fsspec-0.8.4 immutables-0.14 locket-0.2.0 partd-1.1.0

Autenticação Google Cloud

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
#%%bigquery --project home-credit-2-290621 df
#SELECT * FROM home-credit-2-290621.tabelas_manipuladas.modelling_database_1

In [ ]:
project_id = "home-credit-2-290621"
from google.cloud import bigquery
#import humanize
client = bigquery.Client(project=project_id)
 
sql = """
SELECT * FROM home-credit-2-290621.tabelas_manipuladas.modelling_database_1
"""
df = client.query(sql).to_dataframe()

#job = client.get_job()
#bytes_processed = humanize.naturalsize(job.total_bytes_processed, binary=True)
#bytes_billed = humanize.naturalsize(job.total_bytes_billed, binary=True)
#print('%s processed, %s billed (%s)' % (bytes_processed, bytes_billed, job.ended - job.created))

In [ ]:
df.head()

   SK_ID_CURR  ...  delinquency_long_microloan_bureau
0      226605  ...                                NaN
1      198289  ...                                NaN
2      119805  ...                                NaN
3      104932  ...                                NaN
4      383641  ...                                NaN

[5 rows x 265 columns]

In [29]:
# Code to read csv file into Colaboratory:
#!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [5]:
link = 'https://drive.google.com/file/d/1UdadyvfpEuJaar1PspmABkC1HDJtLoYD/view?usp=sharing'

downloaded = drive.CreateFile({'id':"1UdadyvfpEuJaar1PspmABkC1HDJtLoYD"}) 
downloaded.GetContentFile('modelling_table_2.csv')  
df3 = pd.read_csv('modelling_table_2.csv')

In [30]:
link = 'https://drive.google.com/file/d/1whO61fB0nTAXF2El6ehY81TwDt5GtLWW/view?usp=sharing'

downloaded = drive.CreateFile({'id':"1whO61fB0nTAXF2El6ehY81TwDt5GtLWW"}) 
downloaded.GetContentFile('modeling_table_1.csv')  
df2 = pd.read_csv('modeling_table_1.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (87,90) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Criação de entidades

In [40]:
es = ft.EntitySet(id = 'clients')
es = es.entity_from_dataframe(entity_id = 'app', dataframe = df2, index = 'SK_ID_CURR')

#### Definindo colunas para feat engineering

In [17]:
numerical_principal = ['CNT_CHILDREN', 'AMT_INCOME_TOTAL', 
                      'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 
                      'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 
                      'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 
                      'CNT_FAM_MEMBERS', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 
                      'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 
                      'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 
                      'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 
                      'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 
                      'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 
                      'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 
                      'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 
                      'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 
                      'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 
                      'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 
                      'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 
                      'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 
                      'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 
                      'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE',
                      'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 
                      'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3',
                      'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7',
                      'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11',
                      'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15',
                      'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19',
                      'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
                      'AMT_REQ_CREDIT_BUREAU_DAY','AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
                      'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']




categorical_principal = ['NAME_CONTRACT_TYPE','CODE_GENDER', 'FLAG_OWN_CAR', 
              'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE',
              'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 
              'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'REGION_RATING_CLIENT', 
              'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 
              'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE',
              'EMERGENCYSTATE_MODE']

principal = numerical_principal+categorical_principal
len(principal)

120

In [31]:
df2[principal].head()

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
0,0,180000.0,270000.0,13500.0,270000.0,0.046220,-17704,-10896,-3490.0,-1250,NaN,1,1,0,1,0,0,2.0,15,0,0,0,0,0,0,NaN,0.440461,NaN,0.2144,0.0492,0.9811,0.7416,0.0933,0.0400,0.0345,0.4167,0.4583,0.0364,0.1748,0.0749,0.0000,0.0000,0.2185,0.0510,0.9811,0.7517,0.0941,0.0403,0.0345,0.4167,0.4583,0.0372,0.1910,0.0780,0.0000,0.0000,0.2165,0.0492,0.9811,0.7451,0.0938,0.04,0.0345,0.4167,0.4583,0.0370,0.1779,0.0762,0.0000,0.0000,0.1099,0.0,0.0,0.0,0.0,-31.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Revolving loans,F,N,N,Unaccompanied,Commercial associate,Secondary / secondary special,Civil marriage,Municipal apartment,Laborers,1,1,SATURDAY,Industry: type 7,reg oper account,specific housing,"Stone, brick",No
1,1,468000.0,765000.0,38250.0,765000.0,0.072508,-11106,-1247,-5491.0,-3490,1.0,1,1,0,1,0,0,3.0,10,0,0,0,0,0,0,0.660018,0.753449,0.638044,0.3000,0.1296,0.9921,0.8912,0.1724,0.3600,0.1552,0.6667,0.0417,0.0000,0.4892,0.3183,0.0000,0.0659,0.1418,0.0610,0.9921,0.8955,0.0927,0.1611,0.0690,0.6667,0.0417,0.0000,0.2461,0.1542,0.0000,0.0038,0.3029,0.1296,0.9921,0.8927,0.1735,0.36,0.1552,0.6667,0.0417,0.0000,0.4977,0.3241,0.0000,0.0673,0.4122,0.0,0.0,0.0,0.0,-543.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,Revolving loans,M,Y,Y,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,Managers,1,1,SATURDAY,Telecom,reg oper account,block of flats,Panel,No
2,1,427500.0,1042560.0,55674.0,900000.0,0.008625,-12355,-3501,-6081.0,-4684,8.0,1,1,0,1,0,0,3.0,15,0,0,0,0,0,0,NaN,0.554713,NaN,0.1113,0.1636,0.9846,NaN,NaN,0.2056,0.1921,0.3033,NaN,0.1239,NaN,0.1794,NaN,0.0014,0.1134,0.1698,0.9866,NaN,NaN,0.2417,0.2069,0.3333,NaN,0.1267,NaN,0.2354,NaN,0.0000,0.1124,0.1636,0.9866,NaN,NaN,0.24,0.2069,0.3333,NaN,0.1261,NaN,0.2300,NaN,0.0014,0.1777,0.0,0.0,0.0,0.0,-2168.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,Cash loans,M,Y,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,High skill tech staff,2,2,WEDNESDAY,Business Entity Type 3,NaN,block of flats,Panel,No
3,0,117000.0,657000.0,23728.5,657000.0,0.014520,-23113,-3908,-12082.0,-2163,8.0,1,1,0,1,0,0,2.0,9,0,0,0,0,0,0,0.809643,0.221807,0.786267,0.0675,0.0754,0.9861,0.7756,0.0881,0.0000,0.1207,0.1875,0.0417,0.0583,0.0488,0.0640,0.0039,0.0241,0.0620,0.0650,0.9836,0.7844,0.0889,0.0000,0.1034,0.1667,0.0417,0.0111,0.0533,0.0542,0.0039,0.0028,0.0682,0.0754,0.9861,0.7786,0.0886,0.00,0.1207,0.1875,0.0417,0.0594,0.0496,0.0651,0.0039,0.0246,0.0482,1.0,0.0,1.0,0.0,-1378.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0,Cash loans,F,Y,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Accountants,2,2,TUESDAY,Restaurant,reg oper account,block of flats,"Stone, brick",No
4,0,157500.0,486265.5,32517.0,459000.0,0.005084,-21928,-10000,-11679.0,-4288,NaN,1,1,0,1,0,0,1.0,16,0,0,0,0,0,0,NaN,0.515801,0.750375,0.2309,1.0000,0.9841,0.7824,NaN,0.5200,0.4483,0.6667,NaN,0.0675,NaN,0.3174,NaN,0.0000,0.2353,1.0000,0.9841,0.7909,NaN,0.5236,0.4483,0.6667,NaN,0.0690,NaN,0.3307,NaN,0.0000,0.2332,1.0000,0.9841,0.7853,NaN,0.52,0.4483,0.6667,NaN,0.0687,NaN,0.3232,NaN,0.0000,0.4243,4.0,1.0,4.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Cash loans,F,N,Y,Children,State servant,Secondary / secondary special,Widow,House / apartment,Medicine staff,2,2,TUESDAY,Medicine,reg oper account,block of flats,Panel,No

### Construção da matriz de features
- Primitives :Funções que serão aplicadas na criação da matrix de features 
- Com a combinação de no máximo 2 features (max_depth =2)

In [39]:
# Default primitives from featuretools
default_agg_primitives =  ["sum", "std", "max", "skew", "min", "mean", "count", "num_unique", "mode"]
default_trans_primitives =  ['add_numeric', 'multiply_numeric']

feature_matrix, feature_names = ft.dfs(entityset = es, target_entity = 'app',
                                      trans_primitives = default_trans_primitives,
                                       #agg_primitives=default_agg_primitives, 
                                        max_depth = 2, 
                                       primitive_options={
                                        ('add_numeric', 'multiply_numeric'): {
                                        'include_variables': {'app': principal}},                                      
                                        
                                        },
                                       
                                        verbose = True)

feature_matrix = feature_matrix.reset_index()

pd.options.display.max_columns = 1700
feature_matrix.head(10)

/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_CONTRACT_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'CODE_GENDER' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'FLAG_OWN_CAR' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'FLAG_OWN_REALTY' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_TYPE_SUITE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_INCOME_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_EDUCATION_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_FAMILY_STATUS' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'NAME_HOUSING_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'OCCUPATION_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'REGION_RATING_CLIENT' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'REGION_RATING_CLIENT_W_CITY' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'WEEKDAY_APPR_PROCESS_START' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'ORGANIZATION_TYPE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'FONDKAPREMONT_MODE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'HOUSETYPE_MODE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'WALLSMATERIAL_MODE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))
/usr/local/lib/python3.6/dist-packages/featuretools/primitives/options_utils.py:35: UserWarning: Variable 'EMERGENCYSTATE_MODE' not in entity 'app'
  warnings.warn("Variable '%s' not in entity '%s'" % (invalid_var, entity))

KeyboardInterrupt: ignored

In [ ]:
es = ft.EntitySet(id = 'clients')
es = es.entity_from_dataframe(entity_id = 'app', dataframe = df, index = 'SK_ID_CURR')

/usr/local/lib/python3.6/dist-packages/featuretools/entityset/entity.py:600: UserWarning: Using first column as index. To change this, specify the index parameter
  warnings.warn(("Using first column as index. "

In [ ]:
primitives = ft.primitives.list_primitives()
primitives[primitives['type'] == 'transform']

,name,type,dask_compatible,koalas_compatible,description
22,absolute,transform,True,True,Computes the absolute value of a number.
23,isin,transform,True,True,Determines whether a value is present in a pro...
24,scalar_subtract_numeric_feature,transform,True,True,Subtract each value in the list from a given s...
25,cum_min,transform,False,False,Calculates the cumulative minimum.
26,num_words,transform,True,True,Determines the number of words in a string by ...
27,subtract_numeric,transform,True,False,Element-wise subtraction of two lists.
28,add_numeric,transform,True,True,Element-wise addition of two lists.
29,cum_count,transform,False,False,Calculates the cumulative count.
30,weekday,transform,True,True,Determines the day of the week from a datetime.
31,not_equal,transform,True,False,Determines if values in one list are not equal...
32,or,transform,True,True,Element-wise logical OR of two lists.
33,year,transform,True,True,Determines the year value of a datetime.
34,equal,transform,True,True,Determines if values in one list are equal to ...
35,modulo_by_feature,transform,True,True,Return the modulo of a scalar by each element ...
36,week,transform,True,True,Determines the week of the year from a datetime.
37,negate,transform,True,True,Negates a numeric value.
38,haversine,transform,False,False,Calculates the approximate haversine distance ...
39,less_than_equal_to,transform,True,True,Determines if values in one list are less than...
40,modulo_numeric,transform,True,True,Element-wise modulo of two lists.
41,second,transform,True,True,Determines the seconds value of a datetime.
42,day,transform,True,True,Determines the day of the month from a datetime.
43,divide_numeric_scalar,transform,True,True,Divide each element in the list by a scalar.
44,latitude,transform,False,False,Returns the first tuple value in a list of Lat...
45,less_than,transform,True,True,Determines if values in one list are less than...
46,greater_than_equal_to,transform,True,True,Determines if values in one list are greater t...
47,multiply_boolean,transform,True,False,Element-wise multiplication of two lists of bo...
48,not,transform,True,True,Negates a boolean value.
49,time_since_previous,transform,False,False,Compute the time since the previous entry in a...
50,greater_than,transform,True,False,Determines if values in one list are greater t...
51,diff,transform,False,False,Compute the difference between the value in a ...
52,is_null,transform,True,True,Determines if a value is null.
53,multiply_numeric,transform,True,True,Element-wise multiplication of two lists.
54,cum_max,transform,False,False,Calculates the cumulative maximum.
55,multiply_numeric_scalar,transform,True,True,Multiply each element in the list by a scalar.
56,subtract_numeric_scalar,transform,True,True,Subtract a scalar from each element in the list.
57,time_since,transform,True,False,Calculates time from a value to a specified cu...
58,add_numeric_scalar,transform,True,True,Add a scalar to each value in the list.
59,cum_mean,transform,False,False,Calculates the cumulative mean.
60,num_characters,transform,True,True,Calculates the number of characters in a string.
61,cum_sum,transform,False,False,Calculates the cumulative sum.
62,is_weekend,transform,True,True,Determines if a date falls on a weekend.
63,not_equal_scalar,transform,True,True,Determines if values in a list are not equal t...
64,and,transform,True,True,Element-wise logical AND of two lists.
65,equal_scalar,transform,True,True,Determines if values in a list are equal to a ...
66,month,transform,True,True,Determines the month value of a datetime.
67,age,transform,True,False,Calculates the age in years as a floating poin...
68,less_than_equal_to_scalar,transform,True,True,Determines if values are less than or equal to...
69,minute,transform,True,True,Determines the minutes value of a datetime.
70,modulo_numeric_scalar,transform,True,True,Return the modulo of each element in the list ...
71,divide_by_feature,transform,True,True,Divide a scalar by each value in the list.
72,hour,transform,True,True,Determines the hour value of a datetime.
73,less_than_scalar,transform,True,True,Determines if values are less than a given sca...
74,longitude,transform,False,False,Returns the second tuple value in a list of La...
75,divide_numeric,transform,True,True,Element-wise division of two lists.
76,greater_than_equal_to_scalar,transform,True,True,Determines if values are greater than or equal...
77,percentile,transform,False,False,Determines the percentile rank for each value ...
78,greater_than_scalar,transform,True,True,Determines if values are greater than a given ...

In [ ]:
feature_matrix.describe()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,ELEVATORS_AVG,ENTRANCES_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,ELEVATORS_MODE,ENTRANCES_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,cnt_appl_previous,cnt_revolving_previous,cnt_cash_previous,cnt_consumer_previous,avg_amt_annuity_previous,avg_amt_application_previous,avg_amt_credit_previous,avg_amt_down_payment_previous,avg_amt_goods_price_previous,cnt_appl_start_bus_day_previous,cnt_appl_start_weekend_previous,cnt_appl_start_dawn_previous,cnt_appl_start_morning_previous,cnt_appl_start_afternoon_previous,cnt_appl_start_night_previous,min_rate_down_payment_previous,max_interest_rate_primary_previous,max_interest_rate_privileged_previous,cnt_purpose_repair_previous,cnt_purpose_edu_bus_dev_previous,cnt_purpose_medicine_urgent_previous,cnt_purpose_superfluous_previous,cnt_purpose_real_estate_previous,cnt_purpose_house_needs_previous,cnt_purpose_car_previous,cnt_purpose_payment_previous,cnt_approved_contract_previous,cnt_canceled_previous,cnt_refused_previous,cnt_unused_previous,cnt_cash_bank_payment_previous,cnt_cashless_employer_payment_previous,cnt_noncash_account_payment_previous,cnt_unacompanied_suite_previous,cnt_family_suite_previous,cnt_spouse_suite_previous,cnt_group_people_suite_previous,cnt_children_suite_previous,max_client_type_previous,cnt_goods_leisure_previous,cnt_goods_electronic_previous,cnt_goods_vehicles_previous,cnt_goods_superfluous_previous,cnt_goods_medicine_previous,cnt_goods_homeware_previous,cnt_goods_construction_previous,cnt_goods_office_edu_previous,cnt_goods_weapon_previous,cnt_portfolio_cards_previous,cnt_portfolio_cash_previous,cnt_portfolio_pos_previous,cnt_portfolio_cars_previous,cnt_product_xsell_previous,cnt_product_walkin_previous,cnt_channel_regional_previous,cnt_channel_cash_previous,cnt_channel_contact_center_previous,cnt_channel_corporate_car_previous,cnt_seller_electronics_previous,cnt_seller_connectivity_previous,cnt_seller_furniture_previous,cnt_seller_industry_previous,cnt_seller_construction_previous,cnt_seller_superfluous_previous,max_cnt_payment_previous,cnt_yield_low_normal_previous,cnt_yield_low_action_previous,cnt_yield_high_previous,cnt_yield_middle_previous,cnt_insured_on_approval_previous,cnt_historical_credit_card_previous,avg_amt_credit_card_balance_previous,avg_amt_credit_card_credit_limit_previous,avg_amt_credit_card_drawings_atm_previous,avg_amt_credit_card_drawings_previous,avg_amt_credit_card_drawings_other_previous,avg_amt_credit_card_drawings_pos_previous,avg_amt_credit_card_inst_min_regularity_previous,avg_amt_credit_card_payment_previous,avg_amt_credit_card_payment_total_previous,avg_amt_credit_card_receivable_principal_previous,avg_amt_credit_card_recivable_previous,avg_amt_credit_card_total_receivable_previous,avg_cnt_credit_card_drawings_atm_previous,avg_cnt_credit_card_drawings_previous,avg_cnt_credit_card_drawings_other_previous,avg_cnt_credit_card_drawings_pos_previous,avg_cnt_credit_card_instalment_mature_cum_previous,max_credit_card_sk_dpd_previous,max_credit_card_sk_dpd_def_previous,max_credit_card_slope_amt_balance_previous,max_credit_card_slope_amt_credit_limit_previous,max_credit_card_slope_amt_payment_previous,max_installments_gap_days_payment_previous,max_installments_gap_amt_payment_previous,avg_pos_cash_cnt_installment_previous,avg_pos_cash_cnt_installment_future_previous,max_pos_cash_sk_dpd_previous,max_pos_cash_sk_dpd_def_previous
count,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,104582.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307509.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000,151450.00000,127568.000000,157504.000000,103023.000000,143620.000000,152683.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,143620.000000,152683.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,143620.000000,152683.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,159080.000000,306490.000000,306490.000000,306490.000000,306490.000000,307510.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,291057.000000,291057.000000,291057.000000,291057.000000,290640.000000,2.910570e+05,2.910570e+05,2.736050e+05,2.900820e+05,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,273605.000000,4609.000000,4609.000000,291057.0,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,290642.00000,291057.000000,291057.000000,291057.000000,291057.000000,289760.000000,77867.000000,77867.000000,7.786700e+04,5.289200e+04,7.786700e+04,52892.000000,52892.000000,77844.000000,5.283300e+04,7.786700e+04,77867.000000,77867.000000,77867.000000,52892.000000,77867.000000,52892.000000,52892.000000,77844.000000,77867.000000,77867.000000,77867.000000,77867.000000,52839.000000,289398.000000,289398.000000,286902.000000,286902.000000,286902.000000,286902.000000
mean,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,12.061091,0.999997,0.819889,0.199368,0.998133,0.281066,0.056720,2.152665,2.052463,2.031521,12.063419,0.015144,0.050769,0.040659,0.078173,0.230454,0.179555,0.502130,5.143927e-01,0.510853,0.11744,0.088442,0.977735,0.752471,0.078942,0.149725,0.066333,0.100775,0.107399,0.008809,0.028358,0.114231,0.087543,0.977065,0.759637,0.074490,0.145193,0.064958,0.105645,0.105975,0.008076,0.027022,0.117850,0.087955,0.977752,0.755746,0.078078,0.149213,0.067169,0.101954,0.108607,0.008651,0.028236,0.102547,1.422245,0.143421,1.405292,0.100049,-962.858788,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974,4.857128,0.554421,2.153406,2.148225,14532.052781,1.540055e+05,1.700700e+05,7.080503e+03,1.938959e+05,3.674414,1.182713,0.164483,2.348169,2.188901,0.155258,0.047078,0.190258,0.772502,0.0,0.005817,0.031289,0.016746,0.012451,0.003130,0.011527,0.005483,3.044417,0.891375,0.843099,0.078236,3.032739,0.003233,0.024394,1.469248,0.624895,0.197851,0.006628,0.093130,2.578924,0.013846,1.702965,0.031204,0.086639,0.015804,0.178900,0.073374,0.007126,0.000223,0.419110,1.345657,2.035546,0.001306,1.324119,0.440649,1.771248,2.233123,0.832823,0.019934,1.174000,0.818912,0.168235,0.070938,0.087327,0.080046,24.09499,0.944434,0.270006,1.051550,1.116520,0.972681,29.349904,76806.211272,2.250334e+05,1.417957e+04,1.564709e+04,719.780904,9763.168927,3801.207334,2.074366e+04,1.153193e+04,73915.696442,76262.898085,76263.772061,0.642990,1.736082,0.007889,2.055517,7.947027,12.457267,0.448971,0.440633,0.194486,0.385133,37.703619,2940.329119,14.314495,9.792872,8.834884,1.005664
std,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,11.944812,0.001803,0.384280,0.399526,0.043164,0.449521,0.231307,0.910682,0.509034,0.502737,3.265832,0.122126,0.219526,0.197499,0.268444,0.421124,0.383817,0.211062,1.910602e-01,0.194844,0.10824,0.082438,0.059223,0.113280,0.134576,0.100049,0.081184,0.092576,0.110565,0.047732,0.069523,0.107936,0.084307,0.064575,0.110111,0.132256,0.100977,0.081750,0.097880,0.111845,0.046276,0.070254,0.109076,0.082179,0.059897,0.112066,0.134467,0.100368,0.082167,0.093642,0.112260,0.047415,0.070166,0.107462,2.400989,0.446698,2.379803,0.362291,826.808487,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295,4.147042,1.009010,3.231386,1.812148,10007.483472,1.532878e+05,1.657372e+05,1.842180e+04,1.925761e+05,3.547747,1.567005,0.819462,2.807691,2.556038,0.535332,0.084942,0.092137,0.100348,0.0,0.096975,0.236679,0.158721,0.166274,0.070097,0.167093,0.096551,2.124588,1.675430,1.813868,0.326501,2.676267,0.071596,0.200520,1.905564,1.032400,0.559427,0.088200,0.366314,0.775894,0.138191,1.643944,0.204975,0.349685,0.143737,0.492616,0.327193,0.092553,0.016885,0.725548,2.147400,1.685775,0.044851,1.990060,1.097137,1.796607,3.354304,1.227560,0.304497,1.455877,1.239641,0.495389,0.312890,0.363791,0.341185,16.72187,1.303444,0.684983,1.404292,1.384208,1.316675,27.929805,114681.308330,1.978064e+05,2.395232e+04,2.874753e+04,5409.010876,24346.895299,5409.690487,3.148463e+04,2.405440e+04,110754.332456,114030.864974,114031.056816,0.949742,3.933302,0.052291,4.600390,11.184619,120.308842,2.959347,0.032344,0.043475,0.012656,28.620424,16093.531054,7.731747,6.762812,90.206773,4.384726
min,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014568,8.173617e-08,0.000527,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,-2.250000e-01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000015,0.034781,0.373150,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-3230.769231,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,-3230.769231,-3230.769231,-3230.769231,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.103916,-16.000000,-146145.900000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,5.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334007,3.924574e-01,0.370650,0.05770,0.044200,0.976700,0.687200,0.000000,0.069000,0.018700,0.050400,0.045300,0.000000,0.000000,0.052500,0.040700,0.976700,0.699400,0.000000,0.069000,0.016600,0.054200,0.042700,0.000000,0.000000,0.058300,0.043700,0.976700,0.691400,0.000000,0.069000,0.018700,0.051300,0.045700,0.000000,0.000000,0.041200,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,7835.967188,6.192574e+04,6.684943e+04,0.000000e+00,7.355700e+04,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.160716,0.715645,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.00000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,9.000000e+04,1.532022e+03,0.000000e+00,0.000000,0.000000,0.000000,5.810842e+03,0.000000e+00,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.441309,0.189627,0.383490,22.000000,0.000000,9.333333,5.500000,0.000000,0.000000
50%,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,9.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505998,5.659614e-01,0.535276,0.08760,0.076300,0.981600,0.755200,0.000000,0.137900,0.048100,0.075600,0.074500,0.000000,0.003600,0.084000,0.074600,0.981600,0.764800,0.000000,0.137900,0.045800,0.077100,0.073100,0.000000,0.001100,0.086400,0.075800,0.981600,0.758500,0.000000,0.137900,0.048700,0.076100,0.074900,0.000000,0.003100,0.068800,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,0.000000,1.000000,2.000000,11984.355000,1.060020e+05,1.174500e+05,3.375000e+03,1.285912e+05,3.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.189136,0.835095,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.00000,1.000000,0.000000,1.000000,1.000000,1.000000,17.000000,29794.345000,1.617568e+05,6.193738e+03,4.741935e+03,0.000000,1044.297291,1755.131566,1.172179e+04,4.543580e+03,28450.768235,29441.686919,29446.147819,0.333333,0.277778,0.000000,0.142857,3.055556,0.000000,0.000000,0.448747,0.189627,0.384322,31.000000,0.000000,12.000000,7.500000,0.000000,0.000000
75%,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,15.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.675053,6.636171e-01,0.669057,0.14850,0.112200,0.986600,0.823200,0.120000,0.206900,0.085600,0.121000,0.129900,0.003900,0.027700,0.143900,0.112400,0.986600,0.823600,0.120800,0.206900,0.084100,0.131300,0.125200,0.003900,0.023100,0.148900,0.111600,0.986600,0.825600,0.120000,0.206900,0.086800,0.123100,0.130300,0.003900,0.026600,0.127600,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,6.000000,1.000000,3.000000,3.000000,18330.313500,1.912500e+05,2.160720e+05,8.282250e+03,2.449018e+05,5.000000,2.000000,0.000000,3.000000,3.000000,0.000000,0.100023,0.193330,0.852537,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,0.000000,4.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,3.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,3.000000,0.000000,2.000000,0.000000,2.000000,3.000000,1.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,36.00000,1.000000,0.000000,2.000000,2.000000,1.000000,39.000000,108479.830748,2.700000e+05,1.854464e+04,2.115256e+04,0.000000,10894.206024,5430.926974,2.445669e+04,1.350000e+04,104021.960986,107566.981970,107566.981970,0.857143,1.632456,0.000000,2.000000,10.891892,0.000000,0.000000,0.450639,0.193874,0.385166,43.000000,0.000000,18.000000,12.126218,0.000000,0.000000

In [15]:
feature_matrix.to_csv('feat_engineering.csv')

KeyboardInterrupt: ignored

In [ ]:
from google.colab import files
files.download("feat_engineering.csv")

# New Section